GET http://localhost:3000/tasks

###

POST http://localhost:3000/tasks
Content-Type: application/json

{
    "name":"Buy Groceries",
    "frequency":"Weekly",
    "startTime":"08:30",
    "durationHours":"0",
    "durationMinutes":"15",
    "type":"chores",
    "subtasks":["Buy Bread","Buy Milk"],
    "weekdays":"{\"monday\":false,\"tuesday\":true}",
    "monthdays":{}
}

###
GET http://localhost:3000/tasks/62b2f4d4136252e748b6e9d1

###
DELETE http://localhost:3000/tasks/62b2f4d4136252e748b6e9d1

###
PATCH http://localhost:3000/tasks/62b2f4d4136252e748b6e9d1
Content-Type: application/json

{
    "name":"Buy Stuff"
}