GET http://localhost:3000/tasks

###

POST http://localhost:3000/tasks
Content-Type: application/json

{
    "name":"Buy Groceries",
    "frequency":"Weekly",
    "startTime":"08:30",
    "durationHours":"0",
    "durationMinutes":"15",
    "type":"chores",
    "subtasks":["Buy Bread","Buy Milk"],
    "weekdays":"{\"monday\":false,\"tuesday\":true}",
    "monthdays":{}
}

###
GET http://localhost:3000/tasks/62b435b5df1bb92b758e2d0e

###
DELETE http://localhost:3000/tasks/62b435b5df1bb92b758e2d0e

###
PATCH http://localhost:3000/tasks/62b435b5df1bb92b758e2d0e
Content-Type: application/json

{
    "name":"Buy popcorn"
}